// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnimatedButton: typeof import('./components/AnimatedButton.vue')['default']
    CarouselFigure: typeof import('./components/CarouselFigure.vue')['default']
    MButton: typeof import('./components/MButton.vue')['default']
    MCard: typeof import('./components/MCard.vue')['default']
  }
}

export { }
